export const GET_POKEMON_REQUEST: "GET_POKEMON_REQUEST" = "GET_POKEMON_REQUEST";
export const GET_POKEMON_SUCCESS: "GET_POKEMON_SUCCESS" = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_FAILED: "GET_POKEMON_FAILED" = "GET_POKEMON_FAILED";
export const GET_POKEMON_DETAILS_REQUEST: "GET_POKEMON_DETAILS_REQUEST" =
  "GET_POKEMON_DETAILS_REQUEST";
export const GET_POKEMON_DETAILS_SUCCESS: "GET_POKEMON_DETAILS_SUCCESS" =
  "GET_POKEMON_DETAILS_SUCCESS";
export const GET_POKEMON_DETAILS_FAILED: "GET_POKEMON_DETAILS_FAILED" =
  "GET_POKEMON_DETAILS_FAILED";
